#!/bin/bash

set -o monitor

# Backup the existing Me directory, scheduler.json, and keychain.json file
mv ../Me ../Me.test-tmp
touch ../scheduler.json
mv ../scheduler.json ../scheduler.json.test-tmp
touch ../keychain.json
mv ../keychain.json ../keychain.json.test-tmp
# Copy in to place the testing version
cp -R Me ../Me
# Run locker on our mock/fake Me dir
if test -z "$1"; then
    echo "Running local tests"
    vows --spec *-test-local.js;
    rm -rf ../Me
    cp -R Me ../Me
fi

cd ..
node lockerd.js --config tests/config.json > tests/locker.log 2>&1 &
# Wait for the locker to have some startup time
echo "Waiting for the locker to startup..."
sleep 5
cd tests
# Actually run all our tests
if test -n "$1"; then
    echo "Running only tests $1"
    vows --spec $1;
else
    vows --spec *-test.js;
fi
# cleanup
kill -2 %1
fg %1 > /dev/null 2>&1
# Remove the testing Me directory and put the real one back
rm -rf ../Me
mv ../Me.test-tmp ../Me
# Remove the test scheduler.json and put the real one back
rm ../scheduler.json
mv ../scheduler.json.test-tmp ../scheduler.json
# Remove the test keychain.json and put the real one back
rm ../keychain.json
mv ../keychain.json.test-tmp ../keychain.json
