#!/bin/bash

set -o monitor

# Backup the existing Me directory
mv ../Me ../Me.test-tmp
# Copy in to place the testing version
cp -R Me ../Me
# Run locker on our mock/fake Me dir
cd ..
node locker.js > tests/locker.log 2>&1 &
# Wait for the locker to have some startup time
echo "Waiting for the locker to startup..."
sleep 5
cd tests
# Actually run all our tests
if [ -n $1 ]; then
    echo "Running only tests $1"
    vows --spec $1;
else
    vows --spec *-test.js;
fi
# cleanup
kill -2 %1
fg %1 > /dev/null 2>&1
# Remove the testing Me directory and put the real one back
rm -rf ../Me
mv ../Me.test-tmp ../Me
