#!/bin/sh

cd `dirname $0`
scriptlocation=`pwd -P`

PATH=$scriptlocation/bin:$PATH
export PATH

source bin/activate

cd code

echo "Starting up locker..."
if [ -f .1strun ];
then
        node lockerd.js
else
        sh checkEnv.sh 2> .1strun
        node lockerd.js
fi
