var l = require('./longus.js');
l.expand({url:'http://google.com/'},console.log);
l.expand({url:'http://bit.ly/p9p9nm'},console.log);
l.expand({url:'http://t.co/PqXa8AdE'},console.log);
l.expand({url:'hastdftp:g//hgoogleh.chohmh/'},console.log);
l.expand({url:'http://is.gd/e5zJM8'},console.log);
l.expand({url:'http://goo.gl/8cU1F'},console.log);
l.expand({url:'http://budurl.com/wpgm'},console.log);
l.expand({url:'http://sn.im/1eudyy'},console.log);
l.expand({url:'http://tylr.org/post/6759490576'},console.log);
l.expand({url:'http://www.facebook.com/event.php?eid=125829747513209'},console.log);
l.expand({url:'http://nyti.ms/nZ9UYk'},console.log);
