#!/bin/bash

set -e

subdir="$1"
out="$2"
top="$PWD"
builddir="$(mktemp -d tmp.build-XXX)"

rm -rf "$builddir"
mkdir -p "$builddir/$subdir"

trap "rm -rf \"$builddir\"" EXIT

# fetch a clean copy of the code from git
echo "Fetching code..."
# This doesn't work anymore with submodules.  I hate submodules.
scripts/git-archive-all.sh
tar -x -f Locker.tar -C "$builddir/$subdir"
rm Locker.tar

make -C "$builddir/$subdir"
mkdir -p "$builddir/$subdir/Me"

echo "Compressing..."
(cd "$builddir"; tar czf - "$subdir") > "$out"

echo "Done."
echo "$out"
